import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Button } from '@/components/ui/button';
import { 
  Utensils, 
  Dumbbell, 
  Brain, 
  Leaf, 
  Stethoscope, 
  ShoppingBag, 
  Lightbulb, 
  RefreshCw,
  Send,
  Loader2
} from 'lucide-react';
import { followUpQuestion } from '@/lib/api';

interface AIResultDisplayProps {
  plan: string;
  onStartOver: () => void;
}

const SectionCard = ({ title, icon: Icon, content, delay }: { title: string; icon: any; content: string; delay: number }) => (
  <motion.div
    initial={{ opacity: 0, y: 20 }}
    animate={{ opacity: 1, y: 0 }}
    transition={{ delay, duration: 0.5 }}
    className="bg-white rounded-3xl p-6 shadow-sm border border-slate-100 hover:shadow-md transition-shadow"
  >
    <div className="flex items-center gap-3 mb-4">
      <div className="w-10 h-10 rounded-2xl bg-emerald-100 text-emerald-600 flex items-center justify-center">
        <Icon className="w-5 h-5" />
      </div>
      <h3 className="font-display text-xl font-bold text-slate-900">{title}</h3>
    </div>
    <div className="prose prose-slate prose-sm max-w-none text-slate-600 space-y-2 whitespace-pre-wrap">
      {content}
    </div>
  </motion.div>
);

const AIResultDisplay: React.FC<AIResultDisplayProps> = ({ plan, onStartOver }) => {
  const [displayedText, setDisplayedText] = useState('');
  const [isTyping, setIsTyping] = useState(true);
  const [followUp, setFollowUp] = useState('');
  const [chatHistory, setChatHistory] = useState<Array<{ role: 'user' | 'assistant'; content: string }>>([]);
  const [isAsking, setIsAsking] = useState(false);

  // Typing effect
  useEffect(() => {
    let index = 0;
    const interval = setInterval(() => {
      if (index < plan.length) {
        setDisplayedText((prev) => prev + plan.charAt(index));
        index++;
      } else {
        setIsTyping(false);
        clearInterval(interval);
      }
    }, 2); // Fast typing
    return () => clearInterval(interval);
  }, [plan]);

  // Basic section parsing
  const sections = [
    { title: 'Goal Summary', icon: Lightbulb, key: '1.' },
    { title: 'Diet Plan', icon: Utensils, key: '2.' },
    { title: 'Workout Plan', icon: Dumbbell, key: '3.' },
    { title: 'Mental Wellness', icon: Brain, key: '4.' },
    { title: 'Ayurveda / Herbal', icon: Leaf, key: '5.' },
    { title: 'Supplements', icon: Stethoscope, key: '6.' },
    { title: 'Product Suggestions', icon: ShoppingBag, key: '7.' },
    { title: 'Daily Tips', icon: Lightbulb, key: '8.' },
  ];

  const getSectionContent = (key: string, nextKey: string | null) => {
    const start = plan.indexOf(key);
    if (start === -1) return '';
    const end = nextKey ? plan.indexOf(nextKey) : plan.length;
    return plan.substring(start + key.length, end).trim();
  };

  const handleFollowUp = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!followUp.trim() || isAsking) return;

    const currentQuestion = followUp;
    setFollowUp('');
    setIsAsking(true);
    
    const newHistory = [...chatHistory, { role: 'user' as const, content: currentQuestion }];
    setChatHistory(newHistory);

    try {
      const response = await followUpQuestion({
        question: currentQuestion,
        previousContext: [{ role: 'assistant', content: plan }, ...chatHistory]
      });
      setChatHistory([...newHistory, { role: 'assistant', content: response.result }]);
    } catch (error) {
      console.error(error);
    } finally {
      setIsAsking(false);
    }
  };

  return (
    <div className="max-w-4xl mx-auto px-4 py-12 space-y-12">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-3xl font-display font-bold text-slate-900">Your Personalized Health Plan</h2>
          <p className="text-slate-500">Generated by Wellspring AI Health Assistant</p>
        </div>
        <Button 
          variant="outline" 
          onClick={onStartOver}
          className="rounded-full gap-2 text-slate-600"
        >
          <RefreshCw className="w-4 h-4" />
          Start Over
        </Button>
      </div>

      {/* Results Grid */}
      <div className="grid md:grid-cols-2 gap-6">
        {sections.map((section, i) => {
          const content = getSectionContent(section.key, i < sections.length - 1 ? sections[i+1].key : null);
          if (!content && !isTyping) return null;
          return (
            <SectionCard 
              key={section.title} 
              title={section.title} 
              icon={section.icon} 
              content={content} 
              delay={i * 0.1}
            />
          );
        })}
      </div>

      {/* Chat Section */}
      <motion.div 
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ delay: 1 }}
        className="bg-slate-50 rounded-[2.5rem] p-8 space-y-6"
      >
        <h3 className="text-xl font-bold text-slate-900 flex items-center gap-2">
          <Brain className="w-6 h-6 text-emerald-600" />
          Ask a follow-up question
        </h3>

        <div className="space-y-4 max-h-[400px] overflow-y-auto pr-4 scrollbar-thin scrollbar-thumb-slate-200">
          {chatHistory.map((msg, i) => (
            <div key={i} className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}>
              <div className={`max-w-[80%] p-4 rounded-2xl ${
                msg.role === 'user' 
                  ? 'bg-emerald-600 text-white rounded-tr-none' 
                  : 'bg-white text-slate-700 shadow-sm rounded-tl-none'
              }`}>
                <p className="text-sm whitespace-pre-wrap">{msg.content}</p>
              </div>
            </div>
          ))}
          {isAsking && (
            <div className="flex justify-start">
              <div className="bg-white p-4 rounded-2xl rounded-tl-none shadow-sm flex items-center gap-2">
                <Loader2 className="w-4 h-4 animate-spin text-emerald-600" />
                <span className="text-sm text-slate-400">AI is thinking...</span>
              </div>
            </div>
          )}
        </div>

        <form onSubmit={handleFollowUp} className="relative">
          <input
            type="text"
            value={followUp}
            onChange={(e) => setFollowUp(e.target.value)}
            placeholder="Ask me anything about your plan..."
            className="w-full bg-white border border-slate-200 rounded-2xl px-6 py-4 pr-16 focus:outline-none focus:ring-2 focus:ring-emerald-500/20 focus:border-emerald-500 transition-all"
          />
          <button
            type="submit"
            disabled={!followUp.trim() || isAsking}
            className="absolute right-2 top-1/2 -translate-y-1/2 w-12 h-12 bg-emerald-600 text-white rounded-xl flex items-center justify-center hover:bg-emerald-700 disabled:opacity-50 transition-colors shadow-sm"
          >
            <Send className="w-5 h-5" />
          </button>
        </form>
      </motion.div>
    </div>
  );
};

export default AIResultDisplay;
